[tool.bandit]
exclude_dirs = ["/tests"]
skips = ["B608"]

[tool.flake8]
builtins = ["dbutils", "spark", "sc", "sqlContext"]

[tool.pytest.ini_options]
# Pytest configuration for MLOps pipeline tests

# Test discovery patterns
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

# Test paths
testpaths = ["tests"]

# Minimum code coverage requirement
addopts = [
    "--verbose",
    "--strict-markers",
    "--tb=short",
    "--cov=src",
    "--cov-report=term-missing",
    "--cov-report=html",
    "--cov-report=xml",
    "--cov-fail-under=70",
]

# Markers for test categorization
markers = [
    "unit: Unit tests",
    "integration: Integration tests requiring Databricks connection",
    "smoke: Quick smoke tests for basic validation",
    "slow: Tests that take a long time to run",
]


[tool.coverage.run]
source = ["src"]
omit = [
    "*/tests/*",
    "*/test_*.py",
    "*/__pycache__/*",
    "*/site-packages/*",
]

[tool.coverage.report]
precision = 2
show_missing = true
skip_covered = false

[tool.coverage.html]
directory = "htmlcov"

[tool.safety]
# Safety configuration for ignoring MLflow CVE vulnerabilities
ignore-vulnerabilities = [
    71579,  # MLflow CVE-2024-37060
    71693,  # MLflow CVE-2024-37055
    71584,  # MLflow CVE-2024-37056
    71692,  # MLflow CVE-2024-37057
    71578,  # MLflow CVE-2024-37053
    71577,  # MLflow CVE-2024-37052
    71691,  # MLflow CVE-2024-37059
    71587,  # MLflow CVE-2024-37054
]